import { PengawasanData } from "./types";

export const sampleData: PengawasanData[] = [
  {
    id: "1",
    tanggal: "2026-04-01",
    namaPerusahaan: "PT Sinar Abadi",
    namaPemilik: "Budi Santoso",
    alamat: "Jl. Merdeka No. 45, Jakarta",
    jenisUsaha: "Distributor",
    nib: "1234567890123",
    namaPetugas: "Ahmad Fauzi",
    nomorKontak: "081234567890",
    jenisPengawasan: "tdg",
    checklist: {},
    catatan: "Gudang dalam kondisi baik",
    jumlahTemuan: 1,
    jenisPelanggaran: "TDG belum diperpanjang",
    tingkatRisiko: "rendah",
    rekomendasi: ["Pembinaan"],
    status: "selesai",
  },
  {
    id: "2",
    tanggal: "2026-04-02",
    namaPerusahaan: "CV Makmur Jaya",
    namaPemilik: "Siti Rahayu",
    alamat: "Jl. Sudirman No. 12, Bandung",
    jenisUsaha: "Pengecer",
    nib: "9876543210123",
    namaPetugas: "Dewi Lestari",
    nomorKontak: "082345678901",
    jenisPengawasan: "miras",
    checklist: {},
    catatan: "Ditemukan penjualan tanpa izin",
    jumlahTemuan: 3,
    jenisPelanggaran: "Tidak memiliki SIUP-MB",
    tingkatRisiko: "tinggi",
    rekomendasi: ["Teguran", "Rekomendasi Sanksi"],
    status: "tindak_lanjut",
  },
  {
    id: "3",
    tanggal: "2026-04-03",
    namaPerusahaan: "UD Berkah Sejahtera",
    namaPemilik: "Hendra Wijaya",
    alamat: "Jl. Asia Afrika No. 78, Surabaya",
    jenisUsaha: "Grosir",
    nib: "5678901234567",
    namaPetugas: "Ahmad Fauzi",
    nomorKontak: "083456789012",
    jenisPengawasan: "bapokting",
    checklist: {},
    catatan: "Harga sesuai HET",
    jumlahTemuan: 0,
    jenisPelanggaran: "-",
    tingkatRisiko: "rendah",
    rekomendasi: ["Pembinaan"],
    status: "selesai",
  },
  {
    id: "4",
    tanggal: "2026-04-05",
    namaPerusahaan: "PT Kimia Sentosa",
    namaPemilik: "Agus Prabowo",
    alamat: "Jl. Industri No. 22, Semarang",
    jenisUsaha: "Distributor",
    nib: "3456789012345",
    namaPetugas: "Dewi Lestari",
    nomorKontak: "084567890123",
    jenisPengawasan: "b2",
    checklist: {},
    catatan: "Penyimpanan tidak sesuai standar",
    jumlahTemuan: 2,
    jenisPelanggaran: "Label bahaya tidak lengkap",
    tingkatRisiko: "sedang",
    rekomendasi: ["Teguran"],
    status: "proses",
  },
  {
    id: "5",
    tanggal: "2026-04-06",
    namaPerusahaan: "Toko Sembako Murah",
    namaPemilik: "Rina Susanti",
    alamat: "Jl. Pasar Baru No. 3, Medan",
    jenisUsaha: "Pengecer",
    nib: "6789012345678",
    namaPetugas: "Ahmad Fauzi",
    nomorKontak: "085678901234",
    jenisPengawasan: "bapokting",
    checklist: {},
    catatan: "Ditemukan penjualan di atas HET",
    jumlahTemuan: 1,
    jenisPelanggaran: "Penjualan di atas HET",
    tingkatRisiko: "sedang",
    rekomendasi: ["Teguran"],
    status: "tindak_lanjut",
  },
  {
    id: "6",
    tanggal: "2026-04-07",
    namaPerusahaan: "PT Gudang Utama",
    namaPemilik: "Bambang Hartono",
    alamat: "Jl. Pelabuhan No. 55, Makassar",
    jenisUsaha: "Pergudangan",
    nib: "7890123456789",
    namaPetugas: "Dewi Lestari",
    nomorKontak: "086789012345",
    jenisPengawasan: "tdg",
    checklist: {},
    catatan: "Semua dokumen lengkap",
    jumlahTemuan: 0,
    jenisPelanggaran: "-",
    tingkatRisiko: "rendah",
    rekomendasi: ["Pembinaan"],
    status: "selesai",
  },
];
